<a href="https://colab.research.google.com/github/aditigupta217/Statistical_Inference_lab/blob/main/b3_b1_05_practical1_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests
import requests
url = "https://books.toscrape.com/"
response = requests.get('https://books.toscrape.com/')

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.6.17)

In [ ]:
print(response.status_code)

200

In [ ]:

from bs4 import BeautifulSoup

In [ ]:
soup=(BeautifulSoup(response.content,'html.parser'))
print(BeautifulSoup)

<class 'bs4.BeautifulSoup'>

In [ ]:
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [ ]:
import pandas as pd

In [ ]:
print(soup.find('title'))

<title>
    All products | Books to Scrape - Sandbox
</title>

In [ ]:
books = []
for book in soup.find_all("article", class_="product_pod"):
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.find("p", class_="star-rating")["class"][1]

    books.append({
        "Book Name": title,
        "Price": price,
        "Rating": rating
    })
df = pd.DataFrame(books)
print(df)

                                            Book Name   Price Rating
0                                A Light in the Attic  £51.77  Three
1                                  Tipping the Velvet  £53.74    One
2                                          Soumission  £50.10    One
3                                       Sharp Objects  £47.82   Four
4               Sapiens: A Brief History of Humankind  £54.23   Five
5                                     The Requiem Red  £22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  £33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  £17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  £22.60   Four
9                                     The Black Maria  £52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    Two
11                              Shakespeare's Sonnets  £20.66   Four
12                                        Set Me Free  £17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29   Five
14                          Rip it Up and Start Again  £35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  £57.25  Three
16                                               Olio  £23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    One
18                       Libertarianism for Beginners  £51.33    Two
19                            It's Only the Himalayas  £45.17    Two

In [ ]:
images = []

for book in soup.find_all("article", class_="product_pod"):
    image = book.find("img")["src"]
    image_url = "https://books.toscrape.com/" + image.replace("../", "")
    images.append(image_url)

df["Image"] = images

print(df)

                                            Book Name   Price Rating  \
0                                A Light in the Attic  £51.77  Three
1                                  Tipping the Velvet  £53.74    One
2                                          Soumission  £50.10    One
3                                       Sharp Objects  £47.82   Four
4               Sapiens: A Brief History of Humankind  £54.23   Five
5                                     The Requiem Red  £22.65    One
6   The Dirty Little Secrets of Getting Your Dream...  £33.34   Four
7   The Coming Woman: A Novel Based on the Life of...  £17.93  Three
8   The Boys in the Boat: Nine Americans and Their...  £22.60   Four
9                                     The Black Maria  £52.15    One
10     Starving Hearts (Triangular Trade Trilogy, #1)  £13.99    Two
11                              Shakespeare's Sonnets  £20.66   Four
12                                        Set Me Free  £17.46   Five
13  Scott Pilgrim's Precious Little Life (Scott Pi...  £52.29   Five
14                          Rip it Up and Start Again  £35.02   Five
15  Our Band Could Be Your Life: Scenes from the A...  £57.25  Three
16                                               Olio  £23.88    One
17  Mesaerion: The Best Science Fiction Stories 18...  £37.59    One
18                       Libertarianism for Beginners  £51.33    Two
19                            It's Only the Himalayas  £45.17    Two

                                                Image
0   https://books.toscrape.com/media/cache/2c/da/2...
1   https://books.toscrape.com/media/cache/26/0c/2...
2   https://books.toscrape.com/media/cache/3e/ef/3...
3   https://books.toscrape.com/media/cache/32/51/3...
4   https://books.toscrape.com/media/cache/be/a5/b...
5   https://books.toscrape.com/media/cache/68/33/6...
6   https://books.toscrape.com/media/cache/92/27/9...
7   https://books.toscrape.com/media/cache/3d/54/3...
8   https://books.toscrape.com/media/cache/66/88/6...
9   https://books.toscrape.com/media/cache/58/46/5...
10  https://books.toscrape.com/media/cache/be/f4/b...
11  https://books.toscrape.com/media/cache/10/48/1...
12  https://books.toscrape.com/media/cache/5b/88/5...
13  https://books.toscrape.com/media/cache/94/b1/9...
14  https://books.toscrape.com/media/cache/81/c4/8...
15  https://books.toscrape.com/media/cache/54/60/5...
16  https://books.toscrape.com/media/cache/55/33/5...
17  https://books.toscrape.com/media/cache/09/a3/0...
18  https://books.toscrape.com/media/cache/0b/bc/0...
19  https://books.toscrape.com/media/cache/27/a5/2...

In [ ]:
df

,Book Name,Price,Rating,Image
0,A Light in the Attic,£51.77,Three,https://books.toscrape.com/media/cache/2c/da/2...
1,Tipping the Velvet,£53.74,One,https://books.toscrape.com/media/cache/26/0c/2...
2,Soumission,£50.10,One,https://books.toscrape.com/media/cache/3e/ef/3...
3,Sharp Objects,£47.82,Four,https://books.toscrape.com/media/cache/32/51/3...
4,Sapiens: A Brief History of Humankind,£54.23,Five,https://books.toscrape.com/media/cache/be/a5/b...
5,The Requiem Red,£22.65,One,https://books.toscrape.com/media/cache/68/33/6...
6,The Dirty Little Secrets of Getting Your Dream...,£33.34,Four,https://books.toscrape.com/media/cache/92/27/9...
7,The Coming Woman: A Novel Based on the Life of...,£17.93,Three,https://books.toscrape.com/media/cache/3d/54/3...
8,The Boys in the Boat: Nine Americans and Their...,£22.60,Four,https://books.toscrape.com/media/cache/66/88/6...
9,The Black Maria,£52.15,One,https://books.toscrape.com/media/cache/58/46/5...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",£13.99,Two,https://books.toscrape.com/media/cache/be/f4/b...
11,Shakespeare's Sonnets,£20.66,Four,https://books.toscrape.com/media/cache/10/48/1...
12,Set Me Free,£17.46,Five,https://books.toscrape.com/media/cache/5b/88/5...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,£52.29,Five,https://books.toscrape.com/media/cache/94/b1/9...
14,Rip it Up and Start Again,£35.02,Five,https://books.toscrape.com/media/cache/81/c4/8...
15,Our Band Could Be Your Life: Scenes from the A...,£57.25,Three,https://books.toscrape.com/media/cache/54/60/5...
16,Olio,£23.88,One,https://books.toscrape.com/media/cache/55/33/5...
17,Mesaerion: The Best Science Fiction Stories 18...,£37.59,One,https://books.toscrape.com/media/cache/09/a3/0...
18,Libertarianism for Beginners,£51.33,Two,https://books.toscrape.com/media/cache/0b/bc/0...
19,It's Only the Himalayas,£45.17,Two,https://books.toscrape.com/media/cache/27/a5/2...

In [ ]:
url = "https://www.scrapethissite.com/pages/simple/"
response = requests.get('https://www.scrapethissite.com/pages/simple/')

In [ ]:
soup=(BeautifulSoup(response.content,'html.parser'))
print(BeautifulSoup)

<class 'bs4.BeautifulSoup'>

In [ ]:
print(soup.find('title'))

<title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>

In [ ]:
countries = soup.find_all("div", class_="country")

country_list = []
capital_list = []
population_list = []
area_list = []

for country in countries:
    country_list.append(country.find("h3", class_="country-name").get_text(strip=True))
    capital_list.append(country.find("span", class_="country-capital").get_text(strip=True))
    population_list.append(country.find("span", class_="country-population").get_text(strip=True))
    area_list.append(country.find("span", class_="country-area").get_text(strip=True))

df = pd.DataFrame({
    "Country": country_list,
    "Capital": capital_list,
    "Population": population_list,
    "Area": area_list
})

print(df)

                  Country           Capital Population       Area
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

In [ ]:
df

                  Country           Capital Population       Area
0                 Andorra  Andorra la Vella      84000      468.0
1    United Arab Emirates         Abu Dhabi    4975593    82880.0
2             Afghanistan             Kabul   29121286   647500.0
3     Antigua and Barbuda        St. John's      86754      443.0
4                Anguilla        The Valley      13254      102.0
..                    ...               ...        ...        ...
245                 Yemen             Sanaa   23495361   527970.0
246               Mayotte         Mamoudzou     159042      374.0
247          South Africa          Pretoria   49000000  1219912.0
248                Zambia            Lusaka   13460305   752614.0
249              Zimbabwe            Harare   11651858   390580.0

[250 rows x 4 columns]

In [ ]:
url = "https://www.scrapethissite.com/pages/forms/"
response = requests.get('https://www.scrapethissite.com/pages/forms/')

In [ ]:
soup=(BeautifulSoup(response.content,'html.parser'))
print(BeautifulSoup)

<class 'bs4.BeautifulSoup'>

In [ ]:
print(soup.find('title'))

<title>Hockey Teams: Forms, Searching and Pagination | Scrape This Site | A public sandbox for learning web scraping</title>

In [ ]:
rows = soup.find_all("tr", class_="team")

team_name = []
year = []
wins = []
losses = []
ot_losses = []
win_pct = []

for row in rows:
    team_name.append(row.find("td", class_="name").get_text(strip=True))
    year.append(row.find("td", class_="year").get_text(strip=True))
    wins.append(row.find("td", class_="wins").get_text(strip=True))
    losses.append(row.find("td", class_="losses").get_text(strip=True))
    ot_losses.append(row.find("td", class_="ot-losses").get_text(strip=True))
    win_pct.append(row.find("td", class_="pct").get_text(strip=True))

df = pd.DataFrame({
    "Team Name": team_name,
    "Year": year,
    "Wins": wins,
    "Losses": losses,
    "OT Losses": ot_losses,
    "Win %": win_pct
})

print(df)

                Team Name  Year Wins Losses OT Losses  Win %
0           Boston Bruins  1990   44     24             0.55
1          Buffalo Sabres  1990   31     30            0.388
2          Calgary Flames  1990   46     26            0.575
3      Chicago Blackhawks  1990   49     23            0.613
4       Detroit Red Wings  1990   34     38            0.425
5         Edmonton Oilers  1990   37     37            0.463
6        Hartford Whalers  1990   31     38            0.388
7       Los Angeles Kings  1990   46     24            0.575
8   Minnesota North Stars  1990   27     39            0.338
9      Montreal Canadiens  1990   39     30            0.487
10      New Jersey Devils  1990   32     33              0.4
11     New York Islanders  1990   25     45            0.312
12       New York Rangers  1990   36     31             0.45
13    Philadelphia Flyers  1990   33     37            0.412
14    Pittsburgh Penguins  1990   41     33            0.512
15       Quebec Nordiques  1990   16     50              0.2
16        St. Louis Blues  1990   47     22            0.588
17    Toronto Maple Leafs  1990   23     46            0.287
18      Vancouver Canucks  1990   28     43             0.35
19    Washington Capitals  1990   37     36            0.463
20          Winnipeg Jets  1990   26     43            0.325
21          Boston Bruins  1991   36     32             0.45
22         Buffalo Sabres  1991   31     37            0.388
23         Calgary Flames  1991   31     37            0.388
24     Chicago Blackhawks  1991   36     29             0.45

In [ ]:
df.to_csv("hockey.csv")

In [ ]:
url = "https://nitrr.ac.in/aboutcse.php"

In [ ]:
response = requests.get(url,verify=False)

/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'nitrr.ac.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [ ]:
soup=(BeautifulSoup(response.content,'html.parser'))
print(BeautifulSoup)

<class 'bs4.BeautifulSoup'>

In [ ]:
print(soup.find('title'))

<title>::: National Institute of Technology Raipur :::</title>

In [ ]:
faculty = soup.find_all("div", class_="faculty")

faculty_data = []

for person in faculty:
    name = person.find("h4").text.strip()
    designation = person.find_all("p")[0].text.strip()
    qualification = person.find_all("p")[1].text.strip()

    faculty_data.append({
        "Name": name,
        "Qualification": qualification,
        "Designation": designation
    })

df = pd.DataFrame(faculty_data)

print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
df

Empty DataFrame
Columns: []
Index: []